FROM nbelakovski/tnn:gpu
# Switch back to root for installing/uninstalling ml framework
USER root
# Install tensorflow related things. Change this line for use with another machine learning framework
RUN pip3 uninstall -y tensorflow-gpu
RUN pip3 install tensorflow
# Switch to the docker user and his home directory
USER docker
WORKDIR /home/docker
CMD /bin/bash
