# Site settings
title: Topography Neural Net
tag_text: Topography Neural Net
description: Estimating topography of a region from satellite images
url: "https://nbelakovski.github.io/topography_neural_net/"
baseurl: ""

font-awesome-include: false # make this false if you don't need font-awesome

# Build settings
markdown: kramdown
